---
- project:
    merge-mode: squash-merge
    default-branch: main
    check:
      jobs:
        - otc-tox-linters
    gate:
      jobs:
        - otc-tox-linters
    deploy:
      jobs:
        - infra-prod-manage-github
