---
gl-project-config:
  default_branch: main
  description: Zuul configuration for the GL tenant
  homepage: null
  archived: true
  has_issues: true
  has_projects: false
  has_wiki: false
  delete_branch_on_merge: true
  allow_merge_commit: false
  allow_squash_merge: true
  allow_rebase_merge: false
