---
zuul-project-config:
  default_branch: master
  description: Zuul configuration for the Eco tenant
  homepage: null
  language: Shell
  archived: false
  has_issues: true
  has_projects: true
  has_wiki: true
  private: false
  delete_branch_on_merge: true
  allow_merge_commit: false
  allow_squash_merge: true
  allow_rebase_merge: false
  teams:
    maintain:
    pull:
    push:
    admin:
      - eco
  collaborators:
    maintain:
    pull:
    push:
    admin:
  protection_rules: default_zuul
