---
- name: "Update all the supplied repositories in {{ orgs.keys() | list }}"
  when: github_repos__state == 'present'
  with_dict: "{{ orgs }}"
  loop_control:
    loop_var: org
  include_tasks: repo-present.yml
