---
- name: "Update all the supplied repositories in {{ orgs.keys() | list }}"
  when: github_repos_state == 'present'
  with_dict: "{{ orgs }}"
  loop_control:
    loop_var: org
  include_tasks: repo-present.yml

- name: "Update teams in {{ orgs.keys() | list }}"
  when: github_teams_state == 'present'
  with_dict: "{{ orgs }}"
  loop_control:
    loop_var: org
  include_tasks: teams-present.yml
