- hosts: all
  tasks:
    - name: manage people
      opentelekomcloud.gitcontrol.members:
        root: "{{ gitstyring_root_dir }}"
        token: "{{ github_token }}"
      check_mode: true

    - name: manage teams
      opentelekomcloud.gitcontrol.teams:
        root: "{{ gitstyring_root_dir }}"
        token: "{{ github_token }}"
      check_mode: true

    - name: manage repositories
      opentelekomcloud.gitcontrol.repositories:
        root: "{{ gitstyring_root_dir }}"
        token: "{{ github_token }}"
